### DISCUSSION TITLE
Generated FFI convertor always throws NullPointerException

### DISCUSSION THREAD

**Discussion by shivambhavsar** [gobley/gobley#73] [Q&A] [answered]
cargo.toml
```toml
[package]
name = "mobile-uniffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "mobile_uniffi"

[dependencies]
uniffi = { version = "0.28.3", features = [ "cli" ] }
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
ic-agent = "0.38.2"
lazy_static = "1.4"
candid = "0.10.10"
serde = "1.0.213"
serde_json = "1.0.132"
serde_bytes = "0.11.15"
k256 = { version = "0.13.4", default-features = false, features = [
    "std",
    "jwk",
] }
yral-types = { git = "https://github.com/yral-dapp/yral-common.git" }
yral-canisters-common = {git = "https://github.com/yral-dapp/yral-common.git"}
yral-canisters-client = {git = "https://github.com/yral-dapp/yral-common.git"}

[build-dependencies]
uniffi = { version = "0.28.3", features = ["build"] }
```

```rust
#[derive(CandidType, Deserialize, uniffi::Record)]
pub struct PrincipalWrapper {
    pub principal: String,
}

#[derive(CandidType, Deserialize, uniffi::Record)]
pub struct IdentityData {
    pub data: Vec<u8>,
}

#[derive(uniffi::Object)]
pub struct IndividualUserService {
    pub principal: Principal,
    pub agent: Arc<Agent>,
}

#[uniffi::export]
impl IndividualUserService {
    #[uniffi::constructor]
    pub fn new(
        principal_wrapper: PrincipalWrapper,
        identity_data: IdentityData,
    ) -> std::result::Result<IndividualUserService, FfiError> {
        println!("xxxxx Hello, world!");
        let principal = get_principal(principal_wrapper.principal).expect("Invalid Principal");
        let identity = delegated_identity_from_bytes(&identity_data.data.as_slice()).unwrap();
        let agent = Agent::builder()
            .with_url("https://ic0.app/")
            .with_identity(identity)
            .build()
            .expect("Failed to create agent");

        Ok(IndividualUserService {
            principal,
            agent: Arc::new(agent),
        })
    }
}
```

Target SDK - 35
JVM - 21
